import type { INodeProperties } from 'n8n-workflow';

export const typebotUpdateDescription: INodeProperties[] = [
  {
    displayName: 'Bot ID',
    name: 'botId',
    type: 'string',
    required: true,
    default: '',
    displayOptions: { show: { operation: ['typebotUpdate'], resource: ['typebot'] } },
    description: "ID of the bot (returned when it was created or listed)",
  },
  {
    displayName: "Typebot URL",
    name: "typebotUrl",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['typebotUpdate'], resource: ['typebot'] } },
    description: "URL of the published bot. Only re-tested if different from the saved one.",
    routing: { send: { type: "body", property: "typebotUrl" } },
  },
  {
    displayName: "Trigger Type",
    name: "triggerType",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['typebotUpdate'], resource: ['typebot'] } },
    description: "'all' or 'keyword'",
    routing: { send: { type: "body", property: "triggerType" } },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: { show: { operation: ['typebotUpdate'], resource: ['typebot'] } },
    options: [
        {
          displayName: "Debounce Seconds",
          name: "debounceSeconds",
          type: "number",
          default: 0,
          description: "Joins fragmented messages from the contact within this window before processing them as one",
          routing: { send: { type: "body", property: "debounceSeconds" } },
        },
        {
          displayName: "Description",
          name: "description",
          type: "string",
          default: '',
          description: "Bot label shown in the dashboard",
          routing: { send: { type: "body", property: "description" } },
        },
        {
          displayName: "Enabled",
          name: "enabled",
          type: "boolean",
          default: true,
          description: "Whether to turning it off removes the bot from trigger evaluation without deleting it (already-active sessions continue until they expire/end)",
          routing: { send: { type: "body", property: "enabled" } },
        },
        {
          displayName: "Expire Message",
          name: "expireMessage",
          type: "string",
          default: '',
          description: "Message sent when the session expires",
          routing: { send: { type: "body", property: "expireMessage" } },
        },
        {
          displayName: "Expire Minutes",
          name: "expireMinutes",
          type: "number",
          default: 0,
          description: "0 = never expires from inactivity",
          routing: { send: { type: "body", property: "expireMinutes" } },
        },
        {
          displayName: "Finish Message",
          name: "finishMessage",
          type: "string",
          default: '',
          description: "Message sent when the flow ends via Keyword Finish",
          routing: { send: { type: "body", property: "finishMessage" } },
        },
        {
          displayName: "Ignore Groups",
          name: "ignoreGroups",
          type: "boolean",
          default: true,
          description: "Whether to does not trigger the bot on group messages",
          routing: { send: { type: "body", property: "ignoreGroups" } },
        },
        {
          displayName: "Keyword Finish",
          name: "keywordFinish",
          type: "string",
          default: '',
          description: "Word that ends the bot immediately",
          routing: { send: { type: "body", property: "keywordFinish" } },
        },
        {
          displayName: "Stop Bot From Me",
          name: "stopBotFromMe",
          type: "boolean",
          default: false,
          description: "Whether to clears the contact's active session if you send them a manual message while they're talking to the bot",
          routing: { send: { type: "body", property: "stopBotFromMe" } },
        },
        {
          displayName: "Trigger Operator",
          name: "triggerOperator",
          type: "string",
          default: '',
          description: "Required if Trigger Type = 'keyword': contains | equals | startsWith | endsWith | regex",
          routing: { send: { type: "body", property: "triggerOperator" } },
        },
        {
          displayName: "Trigger Value",
          name: "triggerValue",
          type: "string",
          default: '',
          description: "Required if Trigger Type = 'keyword'",
          routing: { send: { type: "body", property: "triggerValue" } },
        },
        {
          displayName: "Typing Delay Ms",
          name: "typingDelayMs",
          type: "number",
          default: 0,
          description: "Shows \"typing...\" for N ms before each batch of replies",
          routing: { send: { type: "body", property: "typingDelayMs" } },
        }
    ],
  }
];
