import type { INodeProperties } from 'n8n-workflow';

export const typebotCreateDescription: INodeProperties[] = [
  {
    displayName: "Typebot URL",
    name: "typebotUrl",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['typebotCreate'], resource: ['typebot'] } },
    description: "URL of the PUBLISHED bot on Typebot (the viewer, e.g. https://typebot.co/my-bot-abc123)",
    routing: { send: { type: "body", property: "typebotUrl" } },
  },
  {
    displayName: "Trigger Type",
    name: "triggerType",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['typebotCreate'], resource: ['typebot'] } },
    description: "'all' (any message without an active session triggers this bot) or 'keyword' (only triggers when it matches Trigger Operator + Trigger Value)",
    routing: { send: { type: "body", property: "triggerType" } },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: { show: { operation: ['typebotCreate'], resource: ['typebot'] } },
    options: [
        {
          displayName: "Debounce Seconds",
          name: "debounceSeconds",
          type: "number",
          default: 0,
          description: "Joins fragmented messages from the contact (that arrived split, one per line) within this window before processing them as one",
          routing: { send: { type: "body", property: "debounceSeconds" } },
        },
        {
          displayName: "Description",
          name: "description",
          type: "string",
          default: '',
          description: "Bot label shown in the dashboard (not visible to the contact)",
          routing: { send: { type: "body", property: "description" } },
        },
        {
          displayName: "Enabled",
          name: "enabled",
          type: "boolean",
          default: true,
          description: "Whether the bot takes part in trigger evaluation. Turned off, the bot stays saved but never fires.",
          routing: { send: { type: "body", property: "enabled" } },
        },
        {
          displayName: "Expire Message",
          name: "expireMessage",
          type: "string",
          default: '',
          description: "Message sent when the session expires (empty = ends silently)",
          routing: { send: { type: "body", property: "expireMessage" } },
        },
        {
          displayName: "Expire Minutes",
          name: "expireMinutes",
          type: "number",
          default: 0,
          description: "Expires the session after N minutes of inactivity. 0 = never.",
          routing: { send: { type: "body", property: "expireMinutes" } },
        },
        {
          displayName: "Finish Message",
          name: "finishMessage",
          type: "string",
          default: '',
          description: "Message sent when the flow ends via Keyword Finish",
          routing: { send: { type: "body", property: "finishMessage" } },
        },
        {
          displayName: "Ignore Groups",
          name: "ignoreGroups",
          type: "boolean",
          default: true,
          description: "Whether to does not trigger the bot on group messages",
          routing: { send: { type: "body", property: "ignoreGroups" } },
        },
        {
          displayName: "Keyword Finish",
          name: "keywordFinish",
          type: "string",
          default: '',
          description: "Word that ends the bot immediately (e.g. \"stop\"), matched case/whitespace-insensitively",
          routing: { send: { type: "body", property: "keywordFinish" } },
        },
        {
          displayName: "Stop Bot From Me",
          name: "stopBotFromMe",
          type: "boolean",
          default: false,
          description: "Whether to if you (API/dashboard) send a manual message to the contact while they're talking to the bot, this clears their active session — the bot stops replying until a new trigger",
          routing: { send: { type: "body", property: "stopBotFromMe" } },
        },
        {
          displayName: "Trigger Operator",
          name: "triggerOperator",
          type: "string",
          default: '',
          description: "Required if Trigger Type = 'keyword': contains | equals | startsWith | endsWith | regex",
          routing: { send: { type: "body", property: "triggerOperator" } },
        },
        {
          displayName: "Trigger Value",
          name: "triggerValue",
          type: "string",
          default: '',
          description: "Required if Trigger Type = 'keyword'. The trigger word/expression.",
          routing: { send: { type: "body", property: "triggerValue" } },
        },
        {
          displayName: "Typing Delay Ms",
          name: "typingDelayMs",
          type: "number",
          default: 0,
          description: "Shows \"typing...\" for N ms before each BATCH of replies (not per individual message within the batch)",
          routing: { send: { type: "body", property: "typingDelayMs" } },
        }
    ],
  }
];
