import type { INodeProperties } from 'n8n-workflow';

export const chatwootSaveDescription: INodeProperties[] = [
  {
    displayName: "Base URL",
    name: "baseUrl",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['chatwootSave'], resource: ['chatwoot'] } },
    description: "URL of your Chatwoot (self-hosted or app.chatwoot.com), without a trailing slash",
    routing: { send: { type: "body", property: "baseUrl" } },
  },
  {
    displayName: "Account ID",
    name: "accountId",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['chatwootSave'], resource: ['chatwoot'] } },
    description: "Chatwoot account ID",
    routing: { send: { type: "body", property: "accountId" } },
  },
  {
    displayName: "Api Token",
    name: "apiToken",
    type: "string",
    typeOptions: { password: true },
    required: true,
    default: '',
    displayOptions: { show: { operation: ['chatwootSave'], resource: ['chatwoot'] } },
    description: "Chatwoot API access token (agent or account profile). Stored as-is (needed to call the Chatwoot API on every message) but never returned once saved, not even masked.",
    routing: { send: { type: "body", property: "apiToken" } },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: { show: { operation: ['chatwootSave'], resource: ['chatwoot'] } },
    options: [
        {
          displayName: "Assinar Mensagens",
          name: "assinarMensagens",
          type: "boolean",
          default: false,
          description: "Whether to prefixes the agent's name (from the Chatwoot webhook) before forwarding the reply to WhatsApp",
          routing: { send: { type: "body", property: "assinarMensagens" } },
        },
        {
          displayName: "Auto Create Inbox",
          name: "autoCreateInbox",
          type: "boolean",
          default: false,
          description: "Whether to true: creates an API-type inbox on the spot, already configured with the callback webhook. False: requires Inbox ID of an existing inbox.",
          routing: { send: { type: "body", property: "autoCreateInbox" } },
        },
        {
          displayName: "Ignorar Grupos",
          name: "ignorarGrupos",
          type: "boolean",
          default: false,
          description: "Whether to does not sync group messages with Chatwoot (neither incoming nor outgoing)",
          routing: { send: { type: "body", property: "ignorarGrupos" } },
        },
        {
          displayName: "Inbox ID",
          name: "inboxId",
          type: "string",
          default: '',
          description: "ID of an existing API-type inbox. Required when Auto Create Inbox is off.",
          routing: { send: { type: "body", property: "inboxId" } },
        },
        {
          displayName: "Inbox Name",
          name: "inboxName",
          type: "string",
          default: '',
          description: "Name given to the inbox when Auto Create Inbox is on. Empty defaults to \"Pulze - {instance}\".",
          routing: { send: { type: "body", property: "inboxName" } },
        },
        {
          displayName: "Iniciar Pendente",
          name: "iniciarPendente",
          type: "boolean",
          default: false,
          description: "Whether to new conversations start as \"pending\" instead of \"open\"",
          routing: { send: { type: "body", property: "iniciarPendente" } },
        },
        {
          displayName: "Reabrir Resolvidas",
          name: "reabrirResolvidas",
          type: "boolean",
          default: false,
          description: "Whether to if the contact's conversation is already \"resolved\" in Chatwoot, toggles its status before posting the new message",
          routing: { send: { type: "body", property: "reabrirResolvidas" } },
        }
    ],
  }
];
