import type { INodeProperties } from 'n8n-workflow';

export const messageFormDescription: INodeProperties[] = [
  {
    displayName: "Number",
    name: "number",
    type: "string",
    required: true,
    default: '',
    placeholder: "5511999999999",
    displayOptions: { show: { operation: ['messageForm'], resource: ['message'] } },
    description: "Recipient: phone number with country and area code, or a full JID",
    routing: { send: { type: "body", property: "number" } },
  },
  {
    displayName: "Message",
    name: "message",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['messageForm'], resource: ['message'] } },
    description: "Text shown above the button",
    routing: { send: { type: "body", property: "message" } },
  },
  {
    displayName: "Button Label",
    name: "buttonLabel",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['messageForm'], resource: ['message'] } },
    description: "Label of the button that opens the form",
    routing: { send: { type: "body", property: "buttonLabel" } },
  },
  {
    displayName: "Flow ID",
    name: "flowId",
    type: "string",
    required: true,
    default: '',
    displayOptions: { show: { operation: ['messageForm'], resource: ['message'] } },
    description: "ID of a Flow published in YOUR WhatsApp Business Manager account. Required on purpose — see the description above about the Flow limitation.",
    routing: { send: { type: "body", property: "flowId" } },
  },
  {
    displayName: 'Options',
    name: 'options',
    type: 'collection',
    placeholder: 'Add Option',
    default: {},
    displayOptions: { show: { operation: ['messageForm'], resource: ['message'] } },
    options: [
        {
          displayName: "CPF Or CNPJ Visible",
          name: "cpfOrCnpjVisible",
          type: "boolean",
          default: false,
          description: "Whether to ask for a Brazilian tax ID (CPF/CNPJ)",
          routing: { send: { type: "body", property: "cpfOrCnpjVisible" } },
        },
        {
          displayName: "Delivery Address Visible",
          name: "deliveryAddressVisible",
          type: "boolean",
          default: false,
          description: "Whether to ask for a delivery address",
          routing: { send: { type: "body", property: "deliveryAddressVisible" } },
        },
        {
          displayName: "Email Visible",
          name: "emailVisible",
          type: "boolean",
          default: true,
          description: "Whether to ask for the email",
          routing: { send: { type: "body", property: "emailVisible" } },
        },
        {
          displayName: "Flow Token",
          name: "flowToken",
          type: "string",
          typeOptions: { password: true },
          default: '',
          description: "Identifies this submission (not the Flow). Empty = Pulze generates a UUID.",
          routing: { send: { type: "body", property: "flowToken" } },
        },
        {
          displayName: "Full Name Visible",
          name: "fullNameVisible",
          type: "boolean",
          default: true,
          description: "Whether to ask for the full name",
          routing: { send: { type: "body", property: "fullNameVisible" } },
        },
        {
          displayName: "Offer Description",
          name: "offerDescription",
          type: "string",
          default: '',
          routing: { send: { type: "body", property: "offerDescription" } },
        },
        {
          displayName: "Offer Name",
          name: "offerName",
          type: "string",
          default: '',
          description: "Offer title shown in the form",
          routing: { send: { type: "body", property: "offerName" } },
        },
        {
          displayName: "Phone Number Visible",
          name: "phoneNumberVisible",
          type: "boolean",
          default: true,
          description: "Whether to ask for the phone number",
          routing: { send: { type: "body", property: "phoneNumberVisible" } },
        },
        {
          displayName: "Screen",
          name: "screen",
          type: "string",
          default: "contact_details",
          description: "Initial screen of the Flow",
          routing: { send: { type: "body", property: "screen" } },
        }
    ],
  }
];
