import type { INodeProperties } from 'n8n-workflow';

import { eventsWebhookCreateDescription } from './webhookCreate';
import { eventsWebhookDeleteDescription } from './webhookDelete';
import { eventsWsConfigGetDescription } from './wsConfigGet';
import { eventsWebhookListDescription } from './webhookList';
import { eventsWsConfigSetDescription } from './wsConfigSet';

const showOnlyForEvents = {
  resource: ['events'],
};

export const eventsDescription: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: showOnlyForEvents,
    },
    options: [
    {
      name: "Create or Update a Webhook",
      value: "webhookCreate",
      action: "Create or update a webhook",
      description: "Registers a URL to receive this instance's events via HTTP POST. Label is the identifier — resending the same label updates the existing webhook's URL/events/state, without counting again toward the 3-per-instance limit. The signing secret used for each HMAC-signed delivery is generated by the server and shown ONLY in this response — it is not shown again later, so save it.",
      routing: { request: { method: "POST", url: '=/events/webhook/{{$parameter.instance}}' } },
    },
    {
      name: "Delete a Webhook",
      value: "webhookDelete",
      action: "Delete a webhook",
      description: "Identified by the Label option (default \"default\"). Idempotent: even if the given label does not exist, the response is 200 with deleted:true — there is no \"webhook not found\" error.",
      routing: { request: { method: "DELETE", url: '=/events/webhook/{{$parameter.instance}}' } },
    },
    {
      name: "Get WebSocket Config",
      value: "wsConfigGet",
      action: "Get websocket config",
      description: "Current configuration of this instance's live WebSocket broadcast — same event catalog as the webhook, delivered over a persistent connection instead of HTTP POST. An instance that never configured anything comes back with the default (off).",
      routing: { request: { method: "GET", url: '=/events/websocket-config/{{$parameter.instance}}' } },
    },
    {
      name: "List Webhooks",
      value: "webhookList",
      action: "List webhooks",
      description: 'Lists the webhooks registered on this instance (up to 3), including each one\'s secret — the same value used to validate the HMAC signature of deliveries',
      routing: { request: { method: "GET", url: '=/events/webhook/{{$parameter.instance}}' } },
    },
    {
      name: "Update WebSocket Config",
      value: "wsConfigSet",
      action: "Update websocket config",
      description: "Turns the WebSocket broadcast on/off and filters which events are delivered. This only controls WHAT is broadcast — it does not open the connection by itself: whoever is connected to Live WebSocket Stream receives the events.",
      routing: { request: { method: "POST", url: '=/events/websocket-config/{{$parameter.instance}}' } },
    }
    ],
    default: "webhookCreate",
  },
  {
    displayName: 'Instance Name or ID',
    name: 'instance',
    type: 'options',
    typeOptions: { loadOptionsMethod: 'getInstances' },
    required: true,
    default: '',
    displayOptions: { show: { resource: ['events'] } },
    description: 'Name of the instance. Choose from the list, or specify a name using an <a href="https://docs.n8n.io/code/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  ...eventsWebhookCreateDescription,
  ...eventsWebhookDeleteDescription,
  ...eventsWsConfigGetDescription,
  ...eventsWebhookListDescription,
  ...eventsWsConfigSetDescription,
];
